kind = "web"
previewPath = "/"
title = "Módulo de Gestión de Inventario"
version = "1.0.0"
id = "artifacts/inventario-ui"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25953

[services.development]
run = "pnpm --filter @workspace/inventario-ui run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/inventario-ui", "run", "build" ]
publicDir = "artifacts/inventario-ui/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25953"
BASE_PATH = "/"
